### ISSUE TITLE
Redirect from http to https doesn't work

### ISSUE THREAD

**Issue by ViktorRubenko** [wkeeling/selenium-wire#171] opened 2020-11-17 10:14 UTC
On this page http://oryxrep.com/ seleniumwire doesn't redirect to https and throws 403 error, while vanilla selenium goes from http to https and loads page successfully.

**Comment by wkeeling** [comment] 2020-11-17 13:43
Thanks for raising this. I notice that it seems to affect Chrome - Firefox seems to redirect correctly.

I'll see if I can find out why the redirect isn't being handled properly.

**Comment by wkeeling** [comment] 2020-12-23 09:07
This issue is being caused by the `Proxy-Connection` HTTP header that is being sent by Chrome and being forwarded by Selenium Wire. The server at oryxrep.com seems to trigger a 403 when it sees the header. Selenium Wire shouldn't be sending this header so we will ensure that the header is filtered out.

**Comment by wkeeling** [comment] 2021-01-02 15:33
Fixed in v3.0.0

**Closed by wkeeling** 2021-01-02 15:33 UTC
