### ISSUE TITLE
OSError: Tunnel connection failed: 403 Forbidden

### ISSUE THREAD

**Issue by pawanpaudel93** [wkeeling/selenium-wire#179] opened 2020-12-07 14:35 UTC
How to solve this error in selenium-wire using proxy ??? It's occurring in Ubuntu 20.04.

@wkeeling

**Comment by pawanpaudel93** [comment] 2020-12-07 14:51
@wkeeling  and why does the pages load too slow while using proxy and loads normally while using without proxy.. Proxies are paid btw..

**Comment by pawanpaudel93** [comment] 2020-12-08 04:17
@wkeeling why doesnot the selenium-wire work with proxy in  selenium options argument rather than specifying proxy in seleniumwire options ???

**Comment by wkeeling** [comment] 2020-12-08 09:15
Thanks for raising this.

Are you able to share the code that creates the webdriver, including the proxy configuration (obviously hide any credentials).

Regarding your question about why Selenium Wire does not work with the proxy in Selenium's own options, this is because Selenium Wire has to use this option to inject it's own transparent proxy which it uses to capture requests. https://github.com/wkeeling/selenium-wire/blob/969fca764191a60794780146a5be45d78032bc0d/seleniumwire/webdriver/browser.py#L35 This means that upstream proxies have to be specified separately, in the Selenium Wire options.

**Comment by pawanpaudel93** [comment] 2020-12-08 11:43
@wkeeling i use this code to create chrome instance.
![image](https://user-images.githubusercontent.com/11836100/101479550-77955200-397a-11eb-9980-4ee7be197fcb.png)
When i use http and https proxy both, for loading the https webpages the pages load so slow that i can't do anything and those error also occurs. But when i use proxy with selenium default options it loads quickly.

**Comment by wkeeling** [comment] 2020-12-08 13:52
Thanks for the info. 

We've seen this behaviour before with certain proxies, although unfortunately I don't yet know what the root cause is. One workaround may be to switch to the [mitmproxy backend](https://github.com/wkeeling/selenium-wire#backends) - as that has been found to significantly improve performance. One problem I can see with that though, is that you're using a custom response handler which isn't supported with the mitmproxy backend at the current time. If that isn't critical and you wanted to try the backend, you'd need to first install the mitmproxy package with:

```
pip install mitmproxy
```

Then set the `backend` option in Selenium Wire's options to `mitmproxy`:
```
sw_options = {
    # ... existing options ...
    'backend': 'mitmproxy'
}
```

**Comment by pawanpaudel93** [comment] 2020-12-08 16:55
@wkeeling  Thank you for your time but see the two screenshot I am getting greater speed without seleniumwire than with seleniumwire. I am using shifter/flipnode paid backconnect proxies....
![image](https://user-images.githubusercontent.com/11836100/101515175-2d29ca80-39a6-11eb-8959-cc12f86da0e1.png)
![image](https://user-images.githubusercontent.com/11836100/101515255-416dc780-39a6-11eb-993d-bf7e495529db.png)

**Comment by pawanpaudel93** [comment] 2020-12-09 14:50
@wkeeling why do you think i am getting OSError: Tunnel connection failed: 403 Forbidden errors and slower speed while using shifter/flipnode backconnect proxies ??? I am getting good speed without using seleniumwire with selenium option and also using seleniumwire but without using proxies with seleniumwire ???

**Comment by wkeeling** [comment] 2020-12-09 17:47
I've not used any backconnect proxies with Selenium Wire so I cannot say for sure. As I mentioned previously, we've seen this issue before with other proxies, but as of yet I have not found the root cause. It seems to occur in Python's `http.client` package when it tries to establish a SSL tunnel with the proxy. But sadly I don't currently have a fix, other than to suggest working around the problem using the mitmproxy backend, or perhaps using SOCKS if that's an option?

**Comment by pawanpaudel93** [comment] 2020-12-09 17:53
@wkeeling on mitmproxy i don't have such errors but I am having a very much slower speed as shown in the speed test image above. Do you know maybe for the slower speed ?? And also why didnot you add custom_response_handler for the mitmproxy backend ???

**Comment by pawanpaudel93** [comment] 2020-12-09 18:16
Can you test why backconnect proxies are slower in seleniumwire??? I can provide you the proxy for testing if we can contact on another platform ?? Should i leave my email or something if you can test it ???

**Comment by wkeeling** [comment] 2020-12-10 09:07
I can have a look into why the backconnect proxies are running more slowly, although it will likely be a couple of weeks before I have enough downtime to investigate that. You can contact me separately at will@zifferent.com if you want to leave the details with me. Regarding your question about the custom response handler, the mitmproxy backend works slightly differently as it runs in a separate subprocess, whereas the default backend runs in the same process. This complicates how we implement the custom response handler in the mitmproxy backend. It's on the todo list :-)

**Comment by pawanpaudel93** [comment] 2020-12-11 07:36
@wkeeling  Thank you for your time. I have a question here https://github.com/wkeeling/selenium-wire/blob/master/seleniumwire/proxy/proxy2.py#L344 why are you using the connect tunneling for both the http and https proxies ?? if self.use_proxy and proxy_config['https'].scheme.startswith('http') is always true if https proxy is given i the config with http or https scheme.

**Comment by wkeeling** [comment] 2020-12-11 09:00
Connect tunnelling is used when the outbound connection is https. The `ProxyAwareHTTPSConnection` will use the `https` configuration from the `proxy` dictionary.

The `and proxy_config['https'].scheme.startswith('http')` is a little confusing but this just ensures that the proxy is not a socks proxy. It may have been better written as `and not and proxy_config['https'].scheme.startswith('socks')`.

**Comment by pawanpaudel93** [comment] 2020-12-11 14:05
@wkeeling this is what I received a response from the proxy provider regarding 503 error 
![image](https://user-images.githubusercontent.com/11836100/101912547-ffcd5e80-3be9-11eb-805e-da8f64324dd3.png)
Maybe this is also slowing speed??

**Comment by wkeeling** [comment] 2020-12-11 15:59
Interesting. Maybe you could try playing with Selenium Wire's [`max_threads`](https://github.com/wkeeling/selenium-wire#all-options) option and use a lower number (the default is 9999). Perhaps start with say 10 and increase/decrease and see what result you get?

**Comment by wkeeling** [comment] 2020-12-12 08:55
It is also worth enabling `connection_keep_alive` in the Selenium Wire options. This will cause Selenium Wire to reuse socket connections which may improve your performance.

**Comment by pawanpaudel93** [comment] 2020-12-12 13:51
@wkeeling no improvement on speed I have tried all selenium wire options.

**Comment by pawanpaudel93** [comment] 2020-12-17 03:29
@wkeeling did you have any chance at trying the proxy I emailed you ??

**Comment by pawanpaudel93** [comment] 2020-12-18 06:42
@wkeeling can you check the spam folder again if my email has landed there ??

**Comment by pawanpaudel93** [comment] 2021-01-13 17:15
@wkeeling https://github.com/wkeeling/selenium-wire/blob/master/seleniumwire/proxy/client.py#L73 see this I think it should be serve_forever.

**Comment by wkeeling** [comment] 2021-01-14 15:52
thanks @pawanpaudel93  - you're right, the API has changed to `serve_forever()`, although `client.py` is no longer in use (it's been replaced by `backend.py`). I've marked `client.py` as deprecated, but it should probably be removed completely especially since it's broken anyway. Thanks for spotting.

**Comment by wkeeling** [comment] 2021-02-06 10:01
Closing this issue since Selenium Wire's upstream proxy handling has been completely reworked in v4. The mitmproxy backend is still available as an option in this version.

**Closed** 2021-02-06 10:02 UTC
