### ISSUE TITLE
time to load site

### ISSUE THREAD

**Issue by siparker** [wkeeling/selenium-wire#26] opened 2019-01-03 21:30 UTC
I am getting some really crazy high load times when using selenium wire.

is there anything that can be done to speed things up?

I am getting several timeouts on pages because they are taking 60+ seconds to load versus the usual 3-5 seconds.

**Comment by wkeeling** [comment] 2019-01-03 21:41
@siparker may possibly be related to #1 ?

Worth trying the workaround for that, which is to set the `disable_encoding` selenium wire option. For your config that should look something like this:


seleniumwire_options = {
    'proxy': {
        'http': 'http://111.222.33.44:1234',
        'https': 'https://111.222.33.44:1234',
    },
    'disable_encoding': True  # Workaround for the slow loading issue
}

driver = webdriver.Chrome(
    chrome_options=options, 
    seleniumwire_options=seleniumwire_options, 
    executable_path=chrome_driver
)

**Comment by siparker** [comment] 2019-01-03 22:00
That has certainly sped things up a little but we are still on approx 30s versus 5

**Comment by wkeeling** [comment] 2019-01-04 08:55
@siparker  Thanks for the info, and also for the offer of help!

Sites will run a little slower through Selenium Wire, although 30s seconds vs 5 does seem very slow. Apart from the extra network "hop" introduced by Selenium Wire which itself will introduce some latency, Selenium Wire has to decrypt all HTTPS traffic passing through it so that it can capture the data. It uses OpenSSL for this, starting the OpenSSL process for every request, and this will obviously add overhead. On Linux, it is not very noticeable, but I notice you're using Windows, and I wonder whether the embedded openssl.exe is running more slowly than the Linux version.

Presumably the site you are testing runs over HTTPS? Do you have access to a HTTP version of the same site? If not, could you test a different site that uses HTTP and see what sort of performance you see? That would help to determine whether openssl.exe is the cause of the problem.

**Comment by wkeeling** [comment] 2019-01-04 08:58
It's also worth turning logging up to DEBUG level in your test and watch what comes through as the test runs. That may give some pointers (e.g. certain requests always taking a long time).

In your test module, ensure you have:

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by wkeeling** [comment] 2019-06-15 08:07
@siparker we recently discovered a bug in Selenium Wire which was significantly hurting performance when loading pages on Windows. The bug meant that certain responses weren't being fully closed off causing the browser to wait for very long periods of time, or timeout completely.

The bug is fixed in v1.0.5. If you get a chance, please upgrade to v1.0.5 and see whether this fixes the issue for you.

**Closed by wkeeling** 2019-06-15 08:07 UTC

**Comment by siparker** [comment] 2019-06-15 14:28
yep, that's a lot faster. Must have been the same issue.
