### ISSUE TITLE
Selenium-wire certificate is not valid

### ISSUE THREAD

**Issue by MrFzovpec** [wkeeling/selenium-wire#137] opened 2020-07-21 08:55 UTC
I'm using Chrome 84, selenium-wire 2.0.0, python 3.7, Mac OS Catalina
I need to connect to the website with https connection, but Chrome tells me, that certificate is not trusted (not valid) and changes https connection to http. I had tried all ways from #31 , but there're no results yet. Could anyone help me?

This is my simple code example

`from seleniumwire import webdriver`
`import time`

`browser = webdriver.Chrome(executable_path='./drivers/chromedriver')`
`browser.get('https://google.com')`
`time.sleep(20)`
`browser.close()`

Results in Chrome (In Russian, sorry)

<img width="1199" alt="Снимок экрана 2020-07-21 в 11 54 34" src="https://user-images.githubusercontent.com/39774736/88034153-f2cfa600-cb48-11ea-977a-ce4e3112fb2f.png">
<img width="1198" alt="Снимок экрана 2020-07-21 в 11 54 44" src="https://user-images.githubusercontent.com/39774736/88034175-f8c58700-cb48-11ea-9f50-bf72831b2036.png">

**Comment by wkeeling** [comment] 2020-07-21 09:12
Does the certificate info give any indication as to why it thinks the certificate is not valid? 

I've just updated Chrome to 84 and tried reproducing, but Chrome indicates that the site is secure. I used `https://www.google.com` however (to prevent a redirect when the `www` is omitted. Can you see if that makes any difference?

**Comment by MrFzovpec** [comment] 2020-07-21 09:18
> Does the certificate info give any indication as to why it thinks the certificate is not valid?
> 
> I've just updated Chrome to 84 and tried reproducing, but Chrome indicates that the site is secure. I used `https://www.google.com` however to prevent a redirect when the `www` is omitted. Can you see if that makes any difference?

I deleted certificate from the macOS keychain to find out the issue, but Chrome tells me just "Certificate of www.google.com is not trusted"

<img width="490" alt="Снимок экрана 2020-07-21 в 12 17 29" src="https://user-images.githubusercontent.com/39774736/88036383-26f89600-cb4c-11ea-914c-86be3d96595f.png">

**Comment by wkeeling** [comment] 2020-07-21 09:21
Thanks. Can you try downloading and reinstalling the root certificate? The certificate is here: https://github.com/wkeeling/selenium-wire/raw/master/seleniumwire/proxy/ca.crt

A fresh install of the latest certificate may resolve perhaps.

**Comment by MrFzovpec** [comment] 2020-07-21 09:28
@wkeeling, mac os keychain also tells me, that this certificate (new) is not trusted.
Maybe there is a problem with certificate only in Mac OS?
<img width="705" alt="Снимок экрана 2020-07-21 в 12 26 06" src="https://user-images.githubusercontent.com/39774736/88037284-5bb91d00-cb4d-11ea-8af3-16d2ec3e2e9f.png">

**Comment by wkeeling** [comment] 2020-07-21 09:32
Hmmm... that's weird. Perhaps it is a Mac OS specific issue with the certificate as you say. I don't have a Mac handy so I'm not able to reproduce (I was using Linux for my previous test above).

It might be worth [switching the backend](https://github.com/wkeeling/selenium-wire#backends) to see whether that allows you to move forward. The mitmproxy backend uses a different root certificate.

**Comment by MrFzovpec** [comment] 2020-07-21 09:36
> Hmmm... that's weird. Perhaps it is a Mac OS specific issue with the certificate as you say. I don't have a Mac handy so I'm not able to reproduce (I was using Linux for my previous test above).
> 
> It might be worth [switching the backend](https://github.com/wkeeling/selenium-wire#backends) to see whether that allows you to move forward. The mitmproxy backend uses a different root certificate.

Won't be any problems if I'll use my custom proxies?

**Comment by MrFzovpec** [comment] 2020-07-21 09:38
So, there is the same problem, but with mitproxy certificate. I'll try to fix it.
<img width="488" alt="Снимок экрана 2020-07-21 в 12 37 09" src="https://user-images.githubusercontent.com/39774736/88038453-e64e4c00-cb4e-11ea-987e-d249175965b9.png">

**Comment by MrFzovpec** [comment] 2020-07-21 10:07
@wkeeling is it possible to use another certificate or default system certificate (I suppose, like in common selenium)?

**Comment by wkeeling** [comment] 2020-07-21 12:41
@MrFzovpec I do not know of a way to do that unfortunately. Have you tried using an alternative browser - e.g. Firefox?

**Comment by vikingliu** [comment] 2020-08-27 05:36
I face the same problem  in  mac os.
url = https://market.m.taobao.com/app/tmall-def/jhsbybt/web/index.html
works in selenium, not valid in selenium-wire.
if you can fix this, it's great help

**Comment by adrianbeloqui** [comment] 2020-09-16 23:43
+1

**Comment by soumyaevan** [comment] 2020-10-27 15:12
I am facing the same issue in mac OS. when opening a site using webdriver from selenium-wire, it is getting not secured

**Comment by masudr4n4** [comment] 2021-04-12 16:11
![image](https://user-images.githubusercontent.com/34313493/114426541-15f82500-9bb2-11eb-8c7a-e65f95a3d16f.png) I also got the same issue in windows 10.

**Comment by wkeeling** [comment] 2021-04-12 17:57
@masudr4n4 Have you [installed](https://github.com/wkeeling/selenium-wire#certificates) Selenium Wire's root certificate as an authority?

**Comment by masudr4n4** [comment] 2021-04-12 18:03
@wkeeling  I am not sure what are you talking about i just installed seleniumwire via pip...How to do that?It does not show me the error if its only selenium

**Comment by wkeeling** [comment] 2021-04-12 18:09
@masudr4n4 Yes it won't show you the error if you're just using Selenium, because Selenium does not intercept and capture requests.

As explained in the [certificates](https://github.com/wkeeling/selenium-wire#certificates) section, if you wish to make the "Not Secure" message disappear, then you'll need to install Selenium Wire's SSL certificate as an authority on your computer. You can grab the certificate [here](https://raw.githubusercontent.com/wkeeling/selenium-wire/master/seleniumwire/ca.crt). Save it as to a file called `ca.crt`, and then go to your browser settings, find the certificates section, and install the certificate in the "authorities" section.

Selenium Wire will function without the certificate being installed, but installing it will ensure that you get a padlock icon in the address bar.

**Comment by ofafa** [comment] 2022-01-15 04:42
I found it could be fixed by changing the configuration in keychain like below:
<img width="517" alt="Screen Shot 2022-01-14 at 11 36 04 PM" src="https://user-images.githubusercontent.com/2339408/149609070-0b269048-43bf-4c91-b02e-bc5e10b3196e.png">
1. go to keychain and find the certificate
2. double click on it
3. click on the right arrow of `Trust` section
4. adjust the trust settings according your scenario

In my case, I need to have https connection to the site I'm scraping to work, so I need to enable SSL, other setting are not important.

**Comment by wkeeling** [comment] 2022-06-13 11:14
Closing this issue for now.

**Closed by wkeeling** 2022-06-13 11:14 UTC

**Comment by cwazuidema** [comment] 2023-03-28 05:29
@MrFzovpec, can you please edit your top post and add @ofafa answer directly in your post?
It will help devs to find the answers directly. Thanks

**Comment by prachib-vision** [comment] 2023-12-21 04:30
i don't want my client to do this manually, is there any way to do it in programmatic way in seleniumwire package only???
