### ISSUE TITLE
Request/Response cycle with an HTTP proxy is ~3x slower than vanilla chromedriver

### ISSUE THREAD

**Issue by itayplav** [wkeeling/selenium-wire#74] opened 2019-10-11 20:32 UTC
Using a the test site `https://icanhazip.com` with 100 requests behind a high speed HTTP proxy server, seleniumwire peaks at around 2.5 iterations per second with `tqdm`

![image](https://user-images.githubusercontent.com/4023066/66682969-30eb8100-ec2b-11e9-9052-1770c3571b83.png)

The same configuration with vanilla chromedriver:

![image](https://user-images.githubusercontent.com/4023066/66682947-27faaf80-ec2b-11e9-98cc-6c9be69502c1.png)

Any way of speeding this up? I tried adding the following flags to seleniumwire options to no avail:

`
'disable_encoding': True,
'verify_ssl': False,
`

The culprit seems to be the http cycle turnaround time. Vanilla chromedriver + proxy:

![image](https://user-images.githubusercontent.com/4023066/66684080-0818bb00-ec2e-11e9-8617-04adb85be654.png)

Seleniumwire + proxy: 

![image](https://user-images.githubusercontent.com/4023066/66684136-31394b80-ec2e-11e9-87ee-8fc0e70b53fc.png)

**Comment by wkeeling** [comment] 2019-10-15 12:28
Thanks for running these tests and highlighting the performance difference.

Yes HTTP I/O is likely to be the cause, mainly because Selenium Wire works by sending requests through it's own embedded proxy server in order to capture data. The overhead of the proxy opening and closing connections slows things down. 

We may be able to optimize the connection handling better, although we'd need to do some analysis first.

Out of curiosity, have you tried running the same test against a non-ssl (http only) site?

**Comment by gitayplav** [comment] 2019-10-22 20:44
> Out of curiosity, have you tried running the same test against a non-ssl (http only) site?

I haven't run it on an HTTP site

**Comment by wkeeling** [comment] 2020-07-17 11:21
There's been a couple of relatively recent changes to Selenium Wire that may improve performance. 

The first is that Selenium Wire now has a configurable connection keep-alive. This is off by default, but it can be turned on with:

```
options = {
    'connection_keep_alive': True  # Allow persistent connections
}
driver = webdriver.Firefox(seleniumwire_options=options)  # Also works with Chrome
```

With keep-alive on, Selenium Wire will attempt to reuse socket connections which will reduce I/O overhead.

The second change is the introduction of mitmproxy as a [backend](https://github.com/wkeeling/selenium-wire#backends). mitmproxy has shown to improve page load times, particularly when using an upstream proxy. If you're still experiencing slow performance after switching on keep-alive, switching the backend to mitmproxy may speed things up.

I will try and get some benchmarks to highlight the improvements.

**Comment by wkeeling** [comment] 2021-03-03 14:48
The core of Selenium Wire has been reworked since this issue was reported. It uses a better performing proxy and relies on asyncio rather than threads. There are also ways a [number of ways](https://github.com/wkeeling/selenium-wire#limiting-request-capture) to speed up Selenium Wire if it's running slowly with certain sites. Closing this issue for now.

**Closed by wkeeling** 2021-03-03 14:48 UTC
