### ISSUE TITLE
driver.header_overrides doesn't work with driver.get()

### ISSUE THREAD

**Issue by jedie** [wkeeling/selenium-wire#7] opened 2018-09-20 09:27 UTC
`driver.wait_for_request()` doesn't work here, see: #6 

So i just use `driver.get()` but `driver.header_overrides` doesn't work with that.

In the logging output there is also not the following entry:

`DEBUG:http://seleniumwire/header_overrides 200`

EDIT: work-a-round, call: `driver._client.set_header_overrides(headers={...})`

**Comment by wkeeling** [comment] 2018-09-20 12:35
The `driver.header_overrides` is a property and so you should be able to set the headers by assigning directly to it:

```
headers = {...}
driver.header_overrides = headers
```

Under the covers it calls `driver._client.set_header_overrides(headers)`.

What happens when you try and directly assign to `driver.header_overrides`?

**Comment by sattva1** [comment] 2019-03-17 14:51
I can confirm the overrides (both `driver.header_overrides` property and `set_header_overrides()` method) are not working with Firefox 65. Although `driver.last_request.headers` shows the overridden header value, in fact FF sends the original header value without modification. This is evident both using Dev Tools' Network pane to examine request headers, as well as checking them on a remote host.

**Comment by wkeeling** [comment] 2019-03-17 15:38
Thanks @sattva1 

The override takes place after Firefox transmits the request, so the dev tools pane would not show the overridden header value. However, the fact that you can see on the remote host that the overridden header has not been set seems to indicate that something is not right.

Are you able to post the code for your test - particularly the code that creates the webdriver and sets up the header overrides. Also, which platform are you running on - Windows/Linux/Mac?

Thanks

**Comment by sattva1** [comment] 2019-03-17 17:07
Thank you for clarification regarding the Dev Tools, I stand corrected. Moreover, after further investigation it turned out the remote host was using the JS test (checking `navigator` properties) rather than request headers. So actually selenium-wire is working as intended.

**Comment by wkeeling** [comment] 2019-03-17 18:02
@sattva1 Thanks for confirming.

**Closed by wkeeling** 2019-03-17 18:02 UTC
