### ISSUE TITLE
Multiple Instances of OpenSSL open up

### ISSUE THREAD

**Issue by arunabhdas1** [wkeeling/selenium-wire#29] opened 2019-01-31 10:44 UTC
We have observed that multiple Instances of OpenSSL open up while the site is loading and subsequently we see "OSError: Tunnel Connection failed: 403 Forbidden" error in the logs.

Is this expected behavior of Selenium wire?

**Comment by wkeeling** [comment] 2019-01-31 16:10
@runabh - how many instances are you seeing? Selenium Wire uses OpenSSL to generate the certificates when first connecting to a remote host over HTTPS. However, subsequent connections to the same host won't trigger OpenSSL again as they will reuse those certificates. 

Can you let me know some details of your environment/test setup. Which OS are you using - Windows? And are you connecting directly to the remote host, or via an upstream proxy server (have you configured Selenium Wire's [proxy](https://github.com/wkeeling/selenium-wire#proxies) settings)?

**Comment by runabh** [comment] 2019-02-01 08:02
@wkeeling - We are seeing 3 instances of OpenSSL triggered.
We are running the code on Windows Server 2016.
Chrome version - 59.0.307 (We've tried the latest version as well)
We are using a proxy server to connect to the website and have configured the same in the code. 

The site does open up, but there is a long delay as the OpenSSL popups take a lot of time. 

The behavior is replicable on Firefox as well. We couldn't try Edge as it is on supported on the OS.

**Comment by runabh** [comment] 2019-02-01 08:16
This is the code

from seleniumwire import webdriver
from seleniumwire.webdriver import ChromeOptions
import time
options = {
    'https': 'proxy detail',
        'disable_encoding': True
}
browser = webdriver.Chrome(seleniumwire_options = options)
browser.header_overrides = { 'Cookie': 'cookie string' }

browser.get('url')

**Comment by wkeeling** [comment] 2019-02-01 08:58
Thanks @runabh . This sounds similar to #26 where the site is slow to load in Windows, and likely caused by OpenSSL. I will do some investigation and see how we can improve the performance.

**Comment by aislaks** [comment] 2020-10-11 18:20
I have also faced the same issue where I am getting "OSError: Tunnel Connection failed: 403 Forbidden" error in the logs.

**Comment by DGaffney** [comment] 2020-12-10 16:42
Also seeing ≈30 of these in quick sequence on Youtube

**Comment by wkeeling** [comment] 2021-02-20 12:52
Closing, as from version 4 Selenium Wire no longer uses the openssl executable for certificate generation. However, if similar behaviour is seen in v4 then the issue can be reopened.

**Closed by wkeeling** 2021-02-20 12:52 UTC
