### ISSUE TITLE
Signal only works in main thread

### ISSUE THREAD

**Issue by Nicolas-Brossard** [wkeeling/selenium-wire#56] opened 2019-06-28 19:30 UTC
Hello again :)

I use selenium-wire, in a Django app.
If I use selenium webdriver, I can start my Django server normaly with "python3 manage.py runserver".
With selenium-wire, I must start the server with this command "python3 manage.py runserver --nothreading --noreload"
The issue seems to be located in proxy.py 

`
/usr/local/lib/python3.7/site-packages/seleniumwire/proxy/storage.py in __init__
        signal.signal(signal.SIGTERM, lambda *_: self.cleanup()) 
`

Thanks a lot.

**Comment by kalaomer** [comment] 2019-07-09 07:03
I've got this same issue :/

**Comment by Nicolas-Brossard** [comment] 2019-07-09 08:09
I've bypass with browsermob until better...

**Comment by wkeeling** [comment] 2019-07-09 19:59
@Nicolas-Brossard thanks for raising this. Is the issue here that you are not able to CTRL-C the Django development server when you're running Selenium Wire from it? Also it would be good to understand how you're using Selenium Wire inside your Django app - are you using it in a view somewhere?

**Comment by Nicolas-Brossard** [comment] 2019-07-10 08:21
Yes with this issue you can't quit or reload normally the Django development server, my selenium function is called when a form into my Django view is submit.
This selenium script is import from a file not directly written in my view.
Thanks @wkeeling

**Comment by wkeeling** [comment] 2019-07-24 18:31
The issue here is probably caused by the signal handlers Selenium Wire uses to clean up cached requests when the test ends. These signal handlers are likely interfering with the Django development server which also tries to use them to quit/reload.

Making clean up on exit configurable may be the best option here. For example:

    webdriver.Firefox(seleniumwire_options={'cleanup_onexit': False})
That way in situations like this it could be disabled. Selenium Wire also does limited clean up on startup, so the cached requests wouldn't grow indefinitely.

I'll look at making that change and update here once done.

**Comment by shr00mie** [comment] 2019-07-29 21:19
same as above.

i suspect main program is splitting this module off as a thread, and i'm also hitting `signal only works in main thread`.

any updates on progress? love you long time.

**Comment by wkeeling** [comment] 2019-07-30 20:34
Version 1.0.7 is now available which contains a fix for this issue. I decided that the best option is to remove the signal handler entirely, and rely upon `driver.quit()` for performing cleanup of temporary storage. Cleanup also happens automatically at test start, should `driver.quit()` not have been called.

Let me know if upgrading to 1.0.7 resolves the issue for you.

@Nicolas-Brossard @shr00mie @kalaomer

**Comment by mmesbah** [comment] 2019-07-31 07:22
Thank you guys,

I have encountered to this problem too. But, updating to 1.0.7 has not solved the problem thoroughly, because `selenium-wire` still uses signal lib in `AdminClient`:

```
 File "/anaconda3/lib/python3.7/site-packages/seleniumwire/webdriver/browser.py", line 27, in __init__
    options=seleniumwire_options
  File "/anaconda3/lib/python3.7/site-packages/seleniumwire/proxy/client.py", line 61, in create_proxy
    signal.signal(signal.SIGTERM, lambda *_: self.destroy_proxy())
  File "/anaconda3/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

```

**Comment by wkeeling** [comment] 2019-07-31 09:47
@mmesbah thanks - looks like I missed that. I'll release a new version asap.

**Comment by shr00mie** [comment] 2019-08-01 16:36
halp me, Obi Juan. You're my only hope!

`Browser init error: signal only works in main thread.`

take us to the promised land of 1.0.8!

**Comment by wkeeling** [comment] 2019-08-01 20:29
Version 1.0.8 is now released. Let me know if you hit any other issues.

**Comment by kalaomer** [comment] 2019-08-02 05:31
Looks like working for me, thanks :)

**Comment by jirispilka** [comment] 2019-08-05 18:10
Working for me as well, many thanks.

**Closed** 2019-08-06 09:28 UTC
