### ISSUE TITLE
502 Bad Gateway (non-SSL)

### ISSUE THREAD

**Issue by jstaczek-isp** [wkeeling/selenium-wire#45] opened 2019-04-23 13:43 UTC
Hi,

I'm seeing what look like random 502 errors with both the Chrome and Firefox webdrivers. Here's a debug log. You'll many successful requests and then a socket timeout. The same test steps work when run manually outside of Selenium, so the website under test doesn't appear to be timing out (unless the socket timeout is very low!). 

I'm able to "reproduce" (random) this on two Windows machines, Windows 10 and Windows Server 2016. This is the latest version of seleniumwire and selenium. 

Is there anything else I can do to try to isolate the issue?

Thanks,

- Jason
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:58996/session/8ae9084f-9687-4800-8640-602d59c94273/element/7460e284-bc23-4c89-ae40-2ddd336bc978/value {"text": "Donkey0", "value": ["D", "o", "n", "k", "e", "y", "0"], "id": "7460e284-bc23-4c89-ae40-2ddd336bc978"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:58996 "POST /session/8ae9084f-9687-4800-8640-602d59c94273/element/7460e284-bc23-4c89-ae40-2ddd336bc978/value HTTP/1.1"
200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:58996/session/8ae9084f-9687-4800-8640-602d59c94273/element {"using": "css selector", "value": "[id=\"LoginButton\"]"}
DEBUG:urllib3.connectionpool:http://127.0.0.1:58996 "POST /session/8ae9084f-9687-4800-8640-602d59c94273/element HTTP/1.1" 200 88
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:58996/session/8ae9084f-9687-4800-8640-602d59c94273/element/53d77fd6-3de0-4a50-86b7-15f722352e8e/click {"id": "53d77fd6-3de0-4a50-86b7-15f722352e8e"}
INFO:seleniumwire.proxy.handler:Capturing request: http://10.1.2.114/
DEBUG:urllib3.connectionpool:http://127.0.0.1:58996 "POST /session/8ae9084f-9687-4800-8640-602d59c94273/element/53d77fd6-3de0-4a50-86b7-15f722352e8e/click HTTP/1.1"
200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
DEBUG:selenium.webdriver.remote.remote_connection:POST http://127.0.0.1:58996/session/8ae9084f-9687-4800-8640-602d59c94273/element {"using": "css selector", "value": "[id=\"ContentPlaceHolder_AddEventLinkButton\"]"}
INFO:seleniumwire.proxy.handler:Capturing response: http://10.1.2.114/ 200 OK
DEBUG:seleniumwire.proxy.handler:http://10.1.2.114/ 200
INFO:seleniumwire.proxy.handler:Capturing request: http://10.1.2.114/Events.aspx
DEBUG:seleniumwire.proxy.handler:code 502, message Bad Gateway
Traceback (most recent call last):
  File "C:\Users\jstaczek\AppData\Local\Programs\Python\Python37\lib\site-packages\seleniumwire\proxy\proxy2.py", line 179, in do_GET
    res = conn.getresponse()
  File "C:\Users\jstaczek\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\jstaczek\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\jstaczek\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\jstaczek\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
DEBUG:seleniumwire.proxy.handler:http://10.1.2.114/Events.aspx 502
DEBUG:urllib3.connectionpool:http://127.0.0.1:58996 "POST /session/8ae9084f-9687-4800-8640-602d59c94273/element HTTP/1.1" 404 324
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request
INFO:seleniumwire.proxy.client:Destroying proxy
DEBUG:selenium.webdriver.remote.remote_connection:DELETE http://127.0.0.1:58996/session/8ae9084f-9687-4800-8640-602d59c94273 {}
DEBUG:urllib3.connectionpool:http://127.0.0.1:58996 "DELETE /session/8ae9084f-9687-4800-8640-602d59c94273 HTTP/1.1" 200 14
DEBUG:selenium.webdriver.remote.remote_connection:Finished Request

**Comment by wkeeling** [comment] 2019-05-14 12:22
@jstaczek-isp thanks for raising this and sorry for not coming back sooner.

I will look at reproducing and report back. Are you using any upstream proxy? Can you also share your code that creates the webdriver with any options etc.

Thanks

**Comment by wkeeling** [comment] 2019-06-15 07:58
I have successfully managed to reproduce this and discovered that, although it was being flushed, the response output stream was not being properly closed. This was causing some browser requests to hang and eventually timeout. The issue is Windows specific and does not occur on Linux.

This has been fixed in v1.0.5. Please upgrade to v1.0.5 if you are still experiencing this problem.

**Closed by wkeeling** 2019-06-15 07:58 UTC
